[project]
name = "pingvin-check"
version = "0.5.0"
description = "A lightweight network connectivity checker (ICMP ping + TCP fallback)"
authors = [
    {name = "pvyle0"}
]
requires-python = ">=3.9"

[project.scripts]
pingvin-check = "pingvin.cli:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
asyncio_mode = "auto"